[package]
name = "dome-auxiliary-window"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tracing = "0.1.41"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "block2", "libc", "NSApplication", "NSRunningApplication", "NSWindow", "NSWindowScripting", "NSView", "NSColor", "NSEvent", "NSScreen", "NSResponder", "NSGraphics", "objc2-core-foundation", "objc2-quartz-core"] }
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["std", "CFRunLoop", "CFCGTypes"] }
objc2-quartz-core = { version = "0.3.2", default-features = false, features = ["std", "CALayer"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSObject", "NSArray", "NSEnumerator", "NSGeometry", "NSObjCRuntime", "NSString", "NSValue", "NSDictionary", "NSNotification"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_Foundation", "Win32_UI_HiDpi", "Win32_System_LibraryLoader", "Win32_Graphics_Gdi", "Win32_Graphics_DirectComposition", "Win32_System_Threading", "Win32_Devices_Display"] }
