[book]
title = "Dome"
description = "Just a tiling window manager"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/l0ngvh/Dome"
